# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
  - jekyll-paginate
  - jekyll-feed

exclude: [bundle]

# Permalinks
permalink:        pretty

# Setup
title:            "Mickaël Derriey's blog"
url:              https://mderriey.com

author:           'Mickaël Derriey'

twitter:
  username:       mderriey

logo:             https://s.gravatar.com/avatar/5b8f496ea22d34aee405458d7f8531d2?s=400

paginate:         5

feed:
  path:           atom.xml

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mderriey/
